# Generated by Django 3.2.4 on 2021-06-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='average_rating',
            field=models.TextField(blank=True, db_column='Average Rating', null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.TextField(blank=True, db_column='Genres', null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='user_count',
            field=models.TextField(blank=True, db_column='User Count', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.IntegerField(blank=True, db_column='index', primary_key=True, serialize=False),
        ),
    ]
